#!/bin/bash
#
# gpuci_logger
#
# provides a logging mechanism for scripts to report progress
#
function gpuci_logger {
  TS=`date '+%x %T'`
  MSG_CNT=`echo "$@" | wc -c`
  WIDTH=$((MSG_CNT+6))
  BAR=""
  for ((i = 0 ; i <= $WIDTH ; i++)); do
    BAR="${BAR}─"
  done

  echo -e "\n\e[32mgpuCI logger\e[0m » [$TS]"
  echo -e "\e[32m┌${BAR}┐\e[0m"
  echo -e "\e[32m|    $@    |\e[0m"
  echo -e "\e[32m└${BAR}┘\e[0m\n"
}

gpuci_logger $@
