#!/bin/bash
#
# gpuci_retry
#
# retries a command 3 times after a non-zero exit, waiting 10 seconds
# between attempts. 3 times and 10 seconds are default values which can be
# configured with env vars described below.
#
#   NOTE: source this file to update your bash environment with the settings
#   below. Keep in mind that the calling environment will be modified, so do not
#   set or change the environment here unless the caller expects that.  Also
#   remember that "exit" will exit the calling shell!  Consider rewriting this
#   as a callable script if the functionality below needs to make changes to its
#   environment as a side-effect.
#
# Example usage:
# $ gpuci_retry conda install cudatoolkit=10.0 rapids=0.12
#
# Configurable options are set using the following env vars:
#
# GPUCI_RETRY_MAX       - set to a positive integer to set the max number of retry
#                         attempts (attempts after the initial try).
#                         Default is 3 retries
#
# GPUCI_RETRY_SLEEP     - set to a positive integer to set the duration, in
#                         seconds, to wait between retries.
#                         Default is a 10 second sleep
#

function gpuci_retry {
    command=$1
    shift
    max_retries=${GPUCI_RETRY_MAX:=3}
    retries=0
    sleep_interval=${GPUCI_RETRY_SLEEP:=10}

    ${command} "$@"
    retcode=$?
    while (( retcode != 0 )) && \
          (( retries < max_retries )); do
      ((retries++))
      gpuci_logger "gpuci_retry: retry ${retries} of ${max_retries} | exit code: (${retcode}) -> sleeping for ${sleep_interval} seconds..."
      sleep ${sleep_interval}
      gpuci_logger "gpuci_retry: sleep done -> retrying..."

      ${command} "$@"
      retcode=$?
    done
    return ${retcode}
}

gpuci_retry "$@"
