#!/bin/bash
#
# gpuci_logger
#
# provides a logging mechanism for scripts to report progress
#
function gpuci_logger {
  TS=`date '+%x %T'`
  echo -e "\n"
  echo ">>gpuCI log<< [$TS] $@"
  echo -e "\n"
}

gpuci_logger $@
