#!/bin/bash
# A utility script that examines environment variables provided
# by Jenkins to determine whether a given build is a "nightly", "pull-request",
# or "branch" build.
set -e

echo_build_type() {
  echo -n "$1"
  exit 0
}

# Nightly build:
# For nightly builds, $IS_NIGHTLY is set to "true".
# For other build, IS_NIGHTLY is unset.
if [[ "${IS_NIGHTLY}" = "true" ]]; then
  echo_build_type "nightly"
fi

# PR build from organization members:
# For these builds, GIT_BRANCH is equal to "PR-<NUM>"
# i.e. PR-784
if [[ "${GIT_BRANCH}" =~ ^PR-[0-9]+$ ]]; then
  echo_build_type "pull-request"
fi

# PR build from external contributors (non-organization members):
# For these builds, GIT_BRANCH is equal to "external-pr-<NUM>"
# i.e. external-pr-784
# Technically these builds are branch builds since we copy the
# forked code to the source repository.
if [[ "${GIT_BRANCH}" =~ ^external-pr-[0-9]+$ ]]; then
  echo_build_type "pull-request"
fi

# Branch builds:
# For these builds, GIT_BRANCH is equal to the branch name,
# which can be anything
# i.e. feature-branch-23, branch-22.04, etc.
echo_build_type "branch"
