#!/bin/bash
# A utility script that examines environment variables provided
# by Jenkins to make some environment changes depending on whether
# a nightly or stable build is occurring.
set -e


# Remove nightly channels if we are building main branch
if [[ "${GIT_BRANCH}" = "main" ]]; then
  conda config --system --remove channels rapidsai-nightly
  conda config --system --remove channels dask/label/dev
fi

# If nightly build, append current YYMMDD to version
if [[ "${BUILD_TYPE}" != "pull-request" && "${GIT_BRANCH}" = branch-* ]] ; then
  VERSION_SUFFIX=$(date +%y%m%d)
  export VERSION_SUFFIX
fi

# FIXME: Remove this line once `boa` is properly installed in our CI images
gpuci_mamba_retry install -y -c conda-forge boa
